spring:
  datasource:
      url: jdbc:mysql://localhost:3306/tempcore
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true